# Generated by Django 4.1.7 on 2023-03-12 15:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('profit_margin', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_in_stock', models.IntegerField(default=0)),
                ('minimum_quantity', models.IntegerField(default=0)),
                ('quantity_ordered', models.IntegerField(default=0)),
                ('reorder_quantity', models.IntegerField(default=0)),
                ('rotation', models.IntegerField(default=0)),
                ('on_clearance', models.BooleanField(default=False)),
                ('on_sale', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(default=datetime.datetime(2023, 3, 12, 15, 11, 19, 534645))),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='Product')),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.categories')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('on_delivery', models.BooleanField(default=False)),
                ('on_reorder', models.BooleanField(default=False)),
                ('on_return', models.BooleanField(default=False)),
                ('in_transit', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.product')),
            ],
        ),
    ]
