# Generated by Django 4.1.7 on 2023-03-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='address',
            field=models.CharField(default='Warehouse addresse', max_length=255),
        ),
    ]
