# Generated by Django 4.1.7 on 2023-03-12 15:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 12, 15, 11, 36, 371250)),
        ),
    ]
