# Generated by Django 4.1.7 on 2023-03-13 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_warehouse_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='name',
        ),
    ]
