# Generated by Django 4.1.7 on 2023-03-13 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_remove_stock_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='categories',
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
    ]
