# Generated by Django 4.1.7 on 2023-03-12 16:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_remove_product_unit_price_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 12, 16, 21, 36, 975895, tzinfo=datetime.timezone.utc)),
        ),
    ]
