# Generated by Django 4.1.7 on 2023-03-12 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_threshold'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='unit_price',
        ),
    ]
